In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [11]:
#Logistic Regression
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9425925925925925

In [12]:
#SVM

svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.37222222222222223

In [13]:
#Random Forest

rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9740740740740741

In [14]:
#these above will change as we rerun the train test split to for
#better comparision we use cross validation

In [15]:
#KFold cross validation

In [34]:
#Basic example

from sklearn.model_selection import KFold
kf = KFold(n_splits=6)
kf

KFold(n_splits=6, random_state=None, shuffle=False)

In [35]:
for train_index, test_index in kf.split([11,12,13,14,15,16,17,18,19]):
    print(train_index, test_index)
#kf.split return the indices of training and test data

[2 3 4 5 6 7 8] [0 1]
[0 1 4 5 6 7 8] [2 3]
[0 1 2 3 6 7 8] [4 5]
[0 1 2 3 4 5 7 8] [6]
[0 1 2 3 4 5 6 8] [7]
[0 1 2 3 4 5 6 7] [8]


In [36]:
#Use KFold for our digits example

In [37]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [47]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)
#stratified kfold is like divide the data into folds having all
#representation of classes
#so it is better than k fold methods

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [48]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [49]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [50]:
scores_rf

[0.9248747913188647, 0.9499165275459098, 0.9298831385642737]

In [51]:
#sklearn library has already implemented cross val score that do all
#these things we did above

In [52]:
from sklearn.model_selection import cross_val_score

In [53]:
#Logistic regression model performance using cross_val_score

cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),
                digits.data,
                digits.target,
                cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [54]:
#svm model performance using cross_val_score

cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [58]:
#random forest performance using cross_val_score

cross_val_score(RandomForestClassifier(n_estimators=40),
                digits.data,
                digits.target,
                cv=3)

array([0.92988314, 0.93489149, 0.91986644])

In [59]:
#Parameter tunning using k fold cross validation
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8714618249534452

In [60]:

scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)


0.9359993792675356

In [61]:

scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)


0.9449162011173184

In [62]:

scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9410148975791433